name: Build, Danger

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  statuses: write

jobs:
  danger:
    if: ${{ github.event_name == 'pull_request' }}
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: danger/danger-js@9.1.6
        with:
          args: '--dangerfile ./.github/workflows/dangerfile.js'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: true

  merge_conflict_job:
    runs-on: ubuntu-latest
    name: Find merge conflicts
    needs: danger
    steps:
      - uses: actions/checkout@v2
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v2.0

  lint:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: danger

    steps:
      - name: Restore cached artifacts
        uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: ${{ github.sha }}
      - name: Eslint
        run: npm run lint

  build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Cache artifacts
        uses: actions/cache@v1
        id: cache-build
        with:
          path: '.'
          key: ${{ github.sha }}
